import React from 'react';
import { X, Link2, MapPin, CheckCircle } from 'lucide-react';

interface TaskGuideModalProps {
  isOpen: boolean;
  taskTitle: string;
  onComplete: () => void;
}

export const TaskGuideModal: React.FC<TaskGuideModalProps> = ({
  isOpen,
  taskTitle,
  onComplete
}) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-[60] p-4">
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl w-full max-w-2xl relative transition-colors shadow-2xl overflow-hidden">
        {/* 头部 */}
        <div className="bg-gradient-to-r from-indigo-600 to-purple-600 p-6 text-white">
          <h2 className="text-2xl font-bold mb-2">📋 Task Guide</h2>
          <p className="text-indigo-100 text-sm">Task: {taskTitle}</p>
        </div>

        {/* 内容区域 */}
        <div className="p-6 space-y-6">
          <p className="text-slate-600 dark:text-slate-400 text-sm">
            Congratulations on claiming this task! Before you start promoting, please read the following important reminders:
          </p>

          {/* 提醒 1 */}
          <div className="flex gap-4 p-4 bg-blue-50 dark:bg-blue-950/20 rounded-xl border border-blue-200 dark:border-blue-800">
            <div className="flex-shrink-0 w-10 h-10 bg-blue-500 rounded-full flex items-center justify-center">
              <Link2 size={20} className="text-white" />
            </div>
            <div className="flex-1">
              <h3 className="font-bold text-slate-900 dark:text-white mb-2">
                1. Use Your Tracking Link
              </h3>
              <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
                Please use the exclusive tracking link generated by the system for promotion. This link contains your unique identifier to accurately track click data and conversion results. Do not use other links, otherwise your earnings cannot be calculated correctly.
              </p>
            </div>
          </div>

          {/* 提醒 2 */}
          <div className="flex gap-4 p-4 bg-purple-50 dark:bg-purple-950/20 rounded-xl border border-purple-200 dark:border-purple-800">
            <div className="flex-shrink-0 w-10 h-10 bg-purple-500 rounded-full flex items-center justify-center">
              <MapPin size={20} className="text-white" />
            </div>
            <div className="flex-1">
              <h3 className="font-bold text-slate-900 dark:text-white mb-2">
                2. Submit Your Post Link
              </h3>
              <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
                Submit the link to your published content in "Proof of Work" and clearly indicate the platform (Twitter, Instagram, YouTube, TikTok, etc.). This helps us verify your promotional activities and evaluate their effectiveness.
              </p>
            </div>
          </div>

          {/* 提醒 3 */}
          <div className="flex gap-4 p-4 bg-emerald-50 dark:bg-emerald-950/20 rounded-xl border border-emerald-200 dark:border-emerald-800">
            <div className="flex-shrink-0 w-10 h-10 bg-emerald-500 rounded-full flex items-center justify-center">
              <CheckCircle size={20} className="text-white" />
            </div>
            <div className="flex-1">
              <h3 className="font-bold text-slate-900 dark:text-white mb-2">
                3. Quality Matters
              </h3>
              <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
                The system validates clicks based on your post engagement rate (likes, comments, shares, etc.). Please ensure your promotional content is authentic and high-quality. Avoid using fake traffic or bot clicks, as these will not count as valid clicks.
              </p>
            </div>
          </div>

          {/* 友情提示 */}
          <div className="bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-lg p-4">
            <p className="text-sm text-amber-800 dark:text-amber-200">
              <span className="font-bold">💡 Pro Tip:</span>
              High-quality promotional content and genuine fan engagement are key to earning more. We encourage creative content and sincere recommendations!
            </p>
          </div>
        </div>

        {/* 底部按钮 */}
        <div className="p-6 border-t border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950">
          <button
            onClick={onComplete}
            className="w-full bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white font-bold py-3 rounded-xl transition-all shadow-lg hover:shadow-xl flex items-center justify-center gap-2"
          >
            I Understand, Start Task
            <CheckCircle size={20} />
          </button>
        </div>
      </div>
    </div>
  );
};
